name: stale
on:
  schedule:
    - cron: "30 1 * * *"
permissions:
  contents: read

jobs:
  stale:
    permissions:
      contents: read
      issues: write
      pull-requests: write
    uses: lemonfiber/spec/.github/workflows/stale.yml@61069efc1f0fd09b073b69334c0c07897701a4dd # main
